services:
  anet-keygen:
    image: git.lisenblsh.art/lisenblsh/anet-keygen:latest
    container_name: anet-keygen

  anet-genconf:
    image: git.lisenblsh.art/lisenblsh/anet-genconf:latest
    container_name: anet-genconf
    env_file:
      - .env
    depends_on:
      - anet-keygen #just for build image
    volumes:
      - ./generated-keys:/app/keys
      - ./config:/app/config
 
