name: Build Docker image for anet-auth

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  call-template:
    runs-on: docker
    uses: ./.forgejo/workflows/build-template.yml
    with:
      IMAGE_NAME: anet-auth
