name: Build Docker image for anet-keygen and anet-genconf

on:
  push:
    branches: [ fork ]
    tags: [ "v*" ]
    paths:
      - 'anet-keygen/**'
      - 'anet-genconf/**'
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  NAMESPACE: ${{ secrets.REGISTRY_USER }}
  IMAGE_NAME_KEYGEN: anet-keygen
  IMAGE_NAME_GENCONF: anet-genconf

jobs:
  build:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: fork

      - name: Prepare variables
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)

          echo "MODE=dev" >> $GITHUB_ENV
          echo "SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "VERSION=dev_$SHORT_SHA" >> $GITHUB_ENV

      - name: Install docker into workflow
        run: apt-get update && apt-get install -y docker.io

      - name: Login to Forgejo Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login $REGISTRY -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build
        run: |
          docker build \
            --build-arg APP_VERSION=dev \
            -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:$VERSION \
            -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:dev \
            ./$IMAGE_NAME_KEYGEN

          docker build \
            --build-arg APP_VERSION=dev \
              --build-arg REPO=git.lisenblsh.art \
            -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:$VERSION \
            -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:dev \
            ./$IMAGE_NAME_GENCONF

      - name: Push
        run: |
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:$VERSION
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:dev
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:$VERSION
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:dev
