name: Build Docker image for anet-keygen and anet-genconf

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  NAMESPACE: ${{ secrets.REGISTRY_USER }}
  IMAGE_NAME_KEYGEN: anet-keygen
  IMAGE_NAME_GENCONF: anet-genconf

jobs:
  build:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare variables
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)

          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "MODE=release" >> $GITHUB_ENV
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "MODE=edge" >> $GITHUB_ENV
            echo "SHA=$SHORT_SHA" >> $GITHUB_ENV
          fi

      - name: Install docker into workflow
        run: apt-get update && apt-get install -y docker.io

      - name: Login to Forgejo Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login $REGISTRY -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build
        run: |
          if [[ "$MODE" == "release" ]]; then
            docker build \
              --build-arg APP_VERSION=$VERSION \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:$VERSION \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:latest \
              ./$IMAGE_NAME_KEYGEN

            docker build \
              --build-arg APP_VERSION=$VERSION \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:$VERSION \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:latest \
              ./$IMAGE_NAME_GENCONF
          else
            docker build \
              --build-arg APP_VERSION=master \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:$SHA \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:edge \
              ./$IMAGE_NAME_KEYGEN

            docker build \
              --build-arg APP_VERSION=edge \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:$VERSION \
              -t $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:latest \
              ./$IMAGE_NAME_GENCONF
          fi

      - name: Push
        run: |
          if [[ "$MODE" == "release" ]]; then
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:$VERSION
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:latest
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:$VERSION
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:latest
          else
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:$SHA
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_KEYGEN:edge
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:$SHA
            docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME_GENCONF:edge
          fi
