name: Build Docker image for anet-keygen and anet-genconf

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
    paths:
      - 'anet-keygen/**'
      - 'anet-genconf/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_KEYGEN: anet-keygen
  IMAGE_NAME_GENCONF: anet-genconf

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare variables
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)

          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "MODE=release" >> $GITHUB_ENV
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "MODE=edge" >> $GITHUB_ENV
            echo "SHA=$SHORT_SHA" >> $GITHUB_ENV
          fi

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image name
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=$OWNER_LC" >> $GITHUB_ENV

      - name: Build
        run: |

          IMAGE_KEYGEN=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME_KEYGEN }}
          IMAGE_GENCONF=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME_GENCONF }}
          if [[ "$MODE" == "release" ]]; then
            docker build \
              --build-arg APP_VERSION=$VERSION \
              -t $IMAGE_KEYGEN:$VERSION \
              -t $IMAGE_KEYGEN::latest \
              ./$IMAGE_NAME_KEYGEN

            docker build \
              --build-arg APP_VERSION=$VERSION \
              -t $IMAGE_GENCONF:$VERSION \
              -t $IMAGE_GENCONF:latest \
              ./$IMAGE_NAME_GENCONF
          else
            docker build \
              --build-arg APP_VERSION=master \
              -t $IMAGE_KEYGEN:$SHA \
              -t $IMAGE_KEYGEN:edge \
              ./$IMAGE_NAME_KEYGEN

            docker build \
              --build-arg APP_VERSION=edge \
              -t $IMAGE_GENCONF:$SHA \
              -t $IMAGE_GENCONF:edge \
              ./$IMAGE_NAME_GENCONF
          fi

      - name: Push
        run: |
          IMAGE_KEYGEN=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME_KEYGEN }}
          IMAGE_GENCONF=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME_GENCONF }}
          if [[ "$MODE" == "release" ]]; then
            docker push $IMAGE_KEYGEN:$VERSION
            docker push $IMAGE_KEYGEN:latest
            docker push $IMAGE_GENCONF:$VERSION
            docker push $IMAGE_GENCONF:latest
          else
            docker push $IMAGE_KEYGEN:$SHA
            docker push $IMAGE_KEYGEN:edge
            docker push $IMAGE_GENCONF:$SHA
            docker push $IMAGE_GENCONF:edge
          fi
